# Site settings
title: Dang Nguyen Anh Khoa
email: wakandan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My programming blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wakandan.github.io" # the base hostname & protocol for your site
twitter_username: khoadn
github_username:  wakandan

# Build settings
markdown: Kramdown
include: ['_pages']
relative_permalinks: false
paginate: 10
plugins: ['jekyll-paginate']
prose:
  rooturl: '_posts'
  siteurl: 'http://prose.github.io/starter/'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""